### ISSUE TITLE
Load position in new database layout

### ISSUE THREAD

**Issue by jugdemon** [cog-ethz/evertools#4]
Instead of reading the position table, we now load the sensor name and then the 3d data.

**Comment by jugdemon** [comment]
That was trigger happy. It does not everything just yet.

@raweibel I am not sure how to restrict the position data to a specific scene. From where can I get the range of sensor data that belongs to one scene. I.e. how to we record the scene start and stop time?

**Comment by raweibel** [comment]
The scene start and end are recorded in system_data with a sensor called "Scene" in data_orgin with "start" and "end" in data_description, and the time is recorded in system_data (value in system_data is set to null, since it is not needed in this case)

**Comment by jugdemon** [comment]
Thanks for the explanation, I will extract the necessary data.

**Comment by jugdemon** [comment]
Done.
